lnk_MyAccount = "//span[normalize-space()='My Account']"
lnk_Register = "(//a[normalize-space()='Register'])[1]"
txt_FirstName = "(//input[@id='input-firstname'])[1]" 
txt_LastName = "(//input[@id='input-lastname'])[1]"
txt_EMail = "(//input[@id='input-email'])[1]"
txt_Telephone = "(//input[@id='input-telephone'])[1]"
txt_Password = "(//input[@id='input-password'])[1]"
txt_PasswordConfirmer = "(//input[@id='input-confirm'])[1]"
txt_group = "newsletter"
opt_Subscribe = "1"
opt_Policy = "(//input[@name='agree'])[1]"
btn_Continue = "(//input[@value='Continue'])[1]"
lnk_Login = "(//a[normalize-space()='Login'])[1]"
txt_EMailAddress = "(//input[@id='input-email'])[1]"
txt_PasswordLogin = "(//input[@id='input-password'])[1]"
btn_Login = "(//input[@value='Login'])[1]"
lnk_ForgottenPassword = "(//a[normalize-space()='Forgotten Password'])[1]"
txt_EMailAdd = "//input[@id='input-email']"
btn_Contine2 = "(//input[@value='Continue'])[1]"
txt_Search = "(//input[@placeholder='Search'])[1]"
btn_Search = "(//button[@class='btn btn-default btn-lg'])[1]"
lnk_AddToCard = "(//span[@class='hidden-xs hidden-sm hidden-md'][normalize-space()='Add to Cart'])[1]"
lnk_Checkout = "(//span[normalize-space()='Checkout'])[1]"
btn_Checkout = "(//a[@class='btn btn-primary'])[1]"